# Generated by Django 4.2 on 2023-05-05 17:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("review", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userfollows",
            options={"verbose_name_plural": "users followed"},
        ),
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.PositiveSmallIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="C:\\Users\\brico\\Documents\\8_Informatique\\1_Formation python\\Projet 9\\4-Realisation\\20230403_ocp9\\litreview\\media",
            ),
        ),
    ]
