# Generated by Django 4.2 on 2023-05-05 17:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("review", "0002_alter_userfollows_options_alter_review_rating_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="img"),
        ),
    ]
